// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM6AmMkKSHStxG4kUt43rEr6vxHsl01Vs',
    appId: '1:326280868790:web:93c814b54875ad399ec717',
    messagingSenderId: '326280868790',
    projectId: 'notes-4a4b7',
    authDomain: 'notes-4a4b7.firebaseapp.com',
    storageBucket: 'notes-4a4b7.firebasestorage.app',
    measurementId: 'G-2RFNP4BZ5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1A-BZgDe6be7yfSM_vXF3kktcdqD-bo0',
    appId: '1:326280868790:android:ff65089ca29024d69ec717',
    messagingSenderId: '326280868790',
    projectId: 'notes-4a4b7',
    storageBucket: 'notes-4a4b7.firebasestorage.app',
  );
}
