// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXwobIHEPpx75ztCxCtIgrQdBmqIVfre0',
    appId: '1:308167718413:web:54db4f0da4e4c467b58744',
    messagingSenderId: '308167718413',
    projectId: 'first-app-ef671',
    authDomain: 'first-app-ef671.firebaseapp.com',
    databaseURL: 'https://first-app-ef671-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-ef671.firebasestorage.app',
    measurementId: 'G-5CJ34TNSRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUtJNm9kMqbtgNoUvDLC_S7tLqTXdKld0',
    appId: '1:308167718413:android:7a9002332594c704b58744',
    messagingSenderId: '308167718413',
    projectId: 'first-app-ef671',
    databaseURL: 'https://first-app-ef671-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'first-app-ef671.firebasestorage.app',
  );

}